#include <iostream>
#include "ploca.h"

using namespace std;

void ispisiPlocu( Ploca &P, int N )
{
	pair<int, int> x = *P;
	cout << "(" << x.first << ", " << x.second << ") ";
	cout << ~P << " ";

	if( x.first + 1 <= N )
	{
		if( P( make_pair( x.first+1, x.second ) ) == 2 )
			cout << "vertikalna";
		else
		{
			P( make_pair( x.first+1, x.second ) );
			cout << "horizontalna";
		}
	}
	else
		cout << "horizontalna";

	cout << endl;
}


int main( void )
{
	int N = 7;

	Ploca P( N );
	ispisiPlocu( P, N );
	++P; ispisiPlocu( P, N );
	P--; ispisiPlocu( P, N );
	P--; ispisiPlocu( P, N );
	// .......
	// .......
	// ..CC...
	// .......
	// .......
	// .......
	// .......

	cout << P( make_pair( 3, 2 ) ) << endl;
	P >> 180; ispisiPlocu( P, N );
	P >> 270; ispisiPlocu( P, N );
	// .......
	// ..C....
	// .xC....
	// .......
	// .......
	// .......
	// .......

	P--; ispisiPlocu( P, N );
	cout << P( make_pair( 3, 4 ) ) << endl;
	P >> 180; ispisiPlocu( P, N );
	// .......
	// .......
	// .xPx...
	// ..P....
	// .......
	// .......
	// .......
	P >> 270; ispisiPlocu( P, N );
	P >> 180 >> 90 >> 90 >> 180 >> 90; ispisiPlocu( P, N );
	// .......
	// P......
	// Px.x...
	// .......
	// .......
	// .......
	// .......

	Ploca Q( N );
	cout << Q( make_pair( 3, 2 ) ) << Q( make_pair( 2, 2 ) ) << endl;
	cout << ( P == Q ) << endl;
	cout << Q( make_pair( 3, 4 ) ) << Q( make_pair( 3, 3 ) ) << Q( make_pair( 7, 2 ) ) << endl;
	cout << ( P == Q ) << endl;

	return 0;
}
