#include <iostream>
#include "poligon.h"

using namespace std;

int main( void )
{
	Poligon P;

	( P > make_pair( 2, 1 ) ) ^ make_pair( 1, -3 );
	( P ^ make_pair( 3, -4 ) ) ^ make_pair( 2, -6 );
	( P > make_pair( 4, 2 ) ) > make_pair( 1, 4 );
	( P > make_pair( 1, -3 ) ) > make_pair( 4, -1 );

	for( int pas = 1; pas <= 4; ++pas )
	{
		pair<int, int> pozicija = P( string( 1, pas+'0' ) );
		cout << "Pas " << pas << ": pozicija (" << pozicija.first << ", " << pozicija.second << ")" << endl;
	}

	cout << P[ make_pair( 3, 3 ) ] << P[ make_pair( 6, 4 ) ] << P[ make_pair( 4, 2 ) ] << P[ make_pair( 7, 1 ) ] << endl;
	// ........
	// ..4.....
	// ..x.....
	// .1......
	// ........
	// 3..x....
	// x.2.....
	// ........

	P > make_pair( 3, 7 );
	P > make_pair( 2, -2 );
	P > make_pair( 1, -3 );
	P ^ make_pair( 4, -1 );

	cout << endl;
	for( int pas = 1; pas <= 4; ++pas )
	{
		pair<int, int> pozicija = P( string( 1, pas+'0' ) );
		cout << "Pas " << pas << ": pozicija (" << pozicija.first << ", " << pozicija.second << ")" << endl;
	}
	// ........
	// ..4.....
	// ..x.....
	// 1.......
	// ........
	// ..3x....
	// x2......
	// ........

	P ^ make_pair( 3, 5 );
	P > make_pair( 4, -2 );
	P ^ make_pair( 1, 2 );
	P > make_pair( 2, 8 );

	cout << endl;
	for( int pas = 1; pas <= 4; ++pas )
	{
		pair<int, int> pozicija = P( string( 1, pas+'0' ) );
		cout << "Pas " << pas << ": pozicija (" << pozicija.first << ", " << pozicija.second << ")" << endl;
	}
	// ........
	// *.......
	// ..x.....
	// ..3.....
	// ........
	// ...x....
	// x......2
	// ........

	return 0;
}
